### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by strogonoff**
I’ve been maintaining and restructuring docs in my fork (I can’t push to this repository and I need to be able to test how docs appear on project site after markup changes while working on visual styling and formatting). It seems like we hit the merge nightmare scenario now 😂

### CODE REVIEW

**Comment by strogonoff** [comment]
I’ve done a manual merge/rebase before making this PR, the docs should be in the right state in my fork, incorporating the work @opoudjis done in meantime where applicable

**Comment by opoudjis** [comment]
Yes. Clearly I need to coordinate with you better about documentation refactoring; I've just done a major exercise (https://github.com/riboseinc/metanorma-iso/issues/238) of genericising the quickstart and guidance documents, and the iso and standoc readmes. This will have downstream implications for you.

**Comment by opoudjis** [comment]
@strogonoff, should I give you write access to this repo, or should the documents under /docs move to a separate repo?

**Comment by strogonoff** [comment]
@opoudjis 

> I’ve just done a major exercise (#238) of genericising the quickstart and guidance documents, and the iso and standoc readmes

I’ve done a rebase based on your latest changes just before making this PR.

> should I give you write access to this repo, or should the documents under /docs move to a separate repo?

I’d say either choice is OK.

It would be slightly less confusing to potential docs contributors if docs are in the same repo (in which case I’d need to have push access to it, I’ll only touch the docs).

That said Open Project sites can work if docs are in a separate repo, we can keep fresh docs in my fork, I believe I can give you push access to my fork or you can make PRs if you have corrections on docs.

**Comment by opoudjis** [comment]
Actually, I've updated asciiiso-syntax.adoc with the new content, so everything is ok.

**Pull request merged**
